
from dynamic_program import DynamicProgram


if __name__ == '__main__':
    try:
        DP = DynamicProgram()
    except Exception as e:
        print(f"An error occurred: {e}")
